### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by ThatOneSheep** [MovTery/PojavZenithHorizon#145]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

The game crashes whenever I go to miscellaneous settings, Launcher, or experimental in the settings

### Log File / 日志文件

java.lang.ArrayIndexOutOfBoundsException: length=130; index=-1
	at com.movtery.pojavzh.ui.fragment.settings.AbstractSettingsFragment.updateListViewValue(AbstractSettingsFragment.kt:329)
	at com.movtery.pojavzh.ui.fragment.settings.AbstractSettingsFragment.initListView(AbstractSettingsFragment.kt:284)
	at com.movtery.pojavzh.ui.fragment.settings.AbstractSettingsFragment.initListView(AbstractSettingsFragment.kt:268)
	at com.movtery.pojavzh.ui.fragment.settings.LauncherSettingsFragment.onViewCreated(LauncherSettingsFragment.kt:91)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:353)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:284)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:72)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8902)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8848)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1136)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5476)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/912174d1-f49f-4744-8843-b4b0a329a724

### Reproduction Steps / 复现步骤

```markdown
?
```

### Expected Behavior / 预期行为

?

### Android Version / Android 版本

10

### Selected Renderer / 选择的渲染器

None

### App Version / 应用版本

1.3.1

### Additional Information / 其他信息

Huawei P30 Lite, Android 10, arm64-v8a

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
The issue has been fixed. Please wait for the next official update! It will be coming soon. #144
