### ISSUE TITLE
外置登录littleskin登陆出现400错误

### ISSUE THREAD

**Issue by MCBottle** [MovTery/PojavZenithHorizon#185]
### Issue Type / 问题类型

Application Issue / 应用问题

### Issue Description / 问题描述

使用littleskin进行外置登录时出现
(400) {"message":["agent.name must be equal to Minecraft"],"error":"Bad Request","statusCode":400}
报错,无法登陆

### Log File / 日志文件

(2024-10-19 17:20:46) [INFO] <UnpackPrep> caciocavallo: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <UnpackPrep> caciocavallo17: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <UnpackPrep> lwjgl3: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <UnpackPrep> forge_installer: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <UnpackPrep> other_login: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <UnpackPrep> security: Pack is up-to-date with the launcher, continuing...
(2024-10-19 17:20:46) [INFO] <AccountsManager> Reload complete.
(2024-10-19 17:20:50) [INFO] <AccountsManager> Reload complete.
(2024-10-19 17:20:53) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:20:53) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:20:53) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:20:56) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:20:56) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:20:56) [ERROR] <Other Login> currentRegisterUrl:https://littleskin.cn/api/register
(2024-10-19 17:21:11) [ERROR] <Other Login> org.json.JSONException: No value for errorMessage
	at org.json.JSONObject.get(JSONObject.java:403)
	at org.json.JSONObject.getString(JSONObject.java:564)
	at com.movtery.pojavzh.feature.login.OtherLoginApi.callLogin(OtherLoginApi.kt:88)
	at com.movtery.pojavzh.feature.login.OtherLoginApi.login(OtherLoginApi.kt:49)
	at com.movtery.pojavzh.ui.fragment.OtherLoginFragment.lambda$onViewCreated$10$com-movtery-pojavzh-ui-fragment-OtherLoginFragment(OtherLoginFragment.java:125)
	at com.movtery.pojavzh.ui.fragment.OtherLoginFragment$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:930)

(2024-10-19 17:21:14) [ERROR] <Other Login> org.json.JSONException: No value for errorMessage
	at org.json.JSONObject.get(JSONObject.java:403)
	at org.json.JSONObject.getString(JSONObject.java:564)
	at com.movtery.pojavzh.feature.login.OtherLoginApi.callLogin(OtherLoginApi.kt:88)
	at com.movtery.pojavzh.feature.login.OtherLoginApi.login(OtherLoginApi.kt:49)
	at com.movtery.pojavzh.ui.fragment.OtherLoginFragment.lambda$onViewCreated$10$com-movtery-pojavzh-ui-fragment-OtherLoginFragment(OtherLoginFragment.java:125)
	at com.movtery.pojavzh.ui.fragment.OtherLoginFragment$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:930)

### Screenshots or Videos / 截图或视频

![Screenshot_20241019_171019](https://github.com/user-attachments/assets/6bcf9cec-3994-4799-9529-03e273039dd8)

### Reproduction Steps / 复现步骤

```markdown
使用littleskin进行外置登录
```

### Android Version / Android 版本

12

### App Version / 应用版本

1.3.5.1

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

荣耀Dio-An00

### This issue has not been reported before / 这个问题还没有人反馈过

- [x] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
已修复，等待下个版本
https://github.com/MovTery/PojavZenithHorizon/actions/runs/11412822812
